export const completeType = {
  ADD_NEW_TASK: 'ADD_NEW_TASK',
  MASS_ADD_COMPLETED_TASKS: 'MASS_ADD_COMPLETED_TASKS',
  RETURN_TASK: 'RETURN_TASK',
  MOVE_UP_COMPLETED_TASK: 'MOVE_UP_COMPLETED_TASK',
  MOVE_DOWN_COMPLETED_TASK: 'MOVE_DOWN_COMPLETED_TASK',
  SET_TASK_LIST: 'SET_TASK_LIST',
};
